// .github/workflows/update-readme.yml

name: Update Readme with Medium Blogs 

on:
  schedule:    
    - cron: '0 * * * *'  // runs every hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:

  update-readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get Medium Blogs
      uses: gautamkrishnar/blog-post-workflow@master
      with:
        feed_list: "https://medium.com/feed/@myusername"
        
    - name: Update README
      uses: jamesgeorge007/github-activity-readme@master
      env:
        MEDIUM_BLOGS: "```json ${{steps.feed.outputs.feed}} ```"
